import {mkdir, rm, writeFile} from "node:fs/promises";
import {generateFiles} from "fumadocs-openapi";
import {openapi} from "../src/lib/openapi";

const output = "./content/en/api";
const generatedOutput = "./src/lib/generated/openapi-schema.json";
const apiDescription = "Generated API reference from OpenAPI schema";
const methodOrder = new Map([
  ["get", 0],
  ["post", 1],
  ["put", 2],
  ["delete", 3],
  ["patch", 4],
  ["head", 5],
  ["options", 6],
]);

function stripMdxExtension(filePath: string) {
  return filePath.endsWith(".mdx") ? filePath.slice(0, -4) : filePath;
}

function toFlatFileName(value: string) {
  const flattened = value
    .replace(/^\//, "")
    .replace(/[{}]/g, "")
    .replace(/\//g, "-")
    .replace(/[^a-zA-Z0-9-_]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();

  return flattened.length > 0 ? flattened : "root";
}

function toTitleCase(value: string) {
  return value
    .replace(/[-_]/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(" ");
}

function compareByMethod(left: string, right: string) {
  const leftMethod = left.split("-")[0];
  const rightMethod = right.split("-")[0];
  const leftPriority = methodOrder.get(leftMethod) ?? Number.MAX_SAFE_INTEGER;
  const rightPriority = methodOrder.get(rightMethod) ?? Number.MAX_SAFE_INTEGER;

  if (leftPriority !== rightPriority) return leftPriority - rightPriority;
  return left.localeCompare(right);
}

void (async () => {
  // Keep the API section fully generated from OpenAPI.
  await rm(output, {recursive: true, force: true});
  await mkdir(output, {recursive: true});

  await generateFiles({
    input: openapi,
    output,
    per: "operation",
    groupBy: "tag",
    name(entry) {
      if (entry.type === "operation") {
        return `${entry.item.method.toLowerCase()}-${toFlatFileName(entry.item.path)}`;
      }

      return `webhook-${entry.item.method.toLowerCase()}-${toFlatFileName(entry.item.name)}`;
    },
    includeDescription: true,
    beforeWrite(files) {
      for (const file of files) {
        if (!file.path.endsWith(".mdx")) continue;
        file.content = file.content.replaceAll("<br>", "<br />");
      }

      const pagesByTag = new Map<string, string[]>();

      for (const file of files) {
        if (!file.path.endsWith(".mdx")) continue;
        const normalizedPath = file.path.replaceAll("\\", "/");
        const [tag, ...rest] = normalizedPath.split("/");
        if (!tag || rest.length === 0) continue;

        const pagePath = stripMdxExtension(rest.join("/"));
        const existing = pagesByTag.get(tag);
        if (existing) existing.push(pagePath);
        else pagesByTag.set(tag, [pagePath]);
      }

      const tags = Array.from(pagesByTag.keys()).sort((left, right) => left.localeCompare(right));

      const indexCards = tags
        .map((tag) => {
          const pages = pagesByTag.get(tag) ?? [];
          pages.sort(compareByMethod);
          const firstPage = pages[0];
          if (!firstPage) return "";

          return `<Card href="/en/api/${tag}/${firstPage}" title=${JSON.stringify(toTitleCase(tag))} />`;
        })
        .filter((card) => card.length > 0);

      files.push({
        path: "index.mdx",
        content: `---
title: API Reference
description: ${apiDescription}
---

{/* This file was generated by Fumadocs. Do not edit this file directly. Any changes should be made by running the generation command again. */}

<Cards>
${indexCards.join("\n")}
</Cards>
`,
      });

      files.push({
        path: "meta.json",
        content: `${JSON.stringify(
          {
            title: "API Reference",
            description: apiDescription,
            pages: ["index", ...tags.map((tag) => `...${tag}`)],
          },
          null,
          2
        )}\n`,
      });

      for (const tag of tags) {
        const pages = pagesByTag.get(tag) ?? [];
        pages.sort(compareByMethod);

        files.push({
          path: `${tag}/meta.json`,
          content: `${JSON.stringify(
            {
              title: toTitleCase(tag),
              pages,
            },
            null,
            2
          )}\n`,
        });
      }
    },
  });

  // Generate a client-safe processed schema snapshot for static APIPage hydration.
  const schema = await openapi.getSchema("./api.json");
  const serializedSchema = {
    bundled: schema.bundled,
    dereferenced: schema.dereferenced,
  };

  await mkdir("./src/lib/generated", {recursive: true});
  await writeFile(generatedOutput, `${JSON.stringify(serializedSchema)}\n`);
})();
