/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LangSplatRouteImport } from './routes/$lang/$'
import { Route as LangLlmsFullRouteImport } from './routes/$lang/llms/full'
import { Route as LangLlmsSlugDotmdRouteImport } from './routes/$lang/llms/$slug[.]md'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSplatRoute = LangSplatRouteImport.update({
  id: '/$lang/$',
  path: '/$lang/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLlmsFullRoute = LangLlmsFullRouteImport.update({
  id: '/$lang/llms/full',
  path: '/$lang/llms/full',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLlmsSlugDotmdRoute = LangLlmsSlugDotmdRouteImport.update({
  id: '/$lang/llms/$slug.md',
  path: '/$lang/llms/$slug.md',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang/$': typeof LangSplatRoute
  '/api/search': typeof ApiSearchRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/$lang/llms/$slug.md': typeof LangLlmsSlugDotmdRoute
  '/$lang/llms/full': typeof LangLlmsFullRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/$': typeof LangSplatRoute
  '/api/search': typeof ApiSearchRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/$lang/llms/$slug.md': typeof LangLlmsSlugDotmdRoute
  '/$lang/llms/full': typeof LangLlmsFullRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang/$': typeof LangSplatRoute
  '/api/search': typeof ApiSearchRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/$lang/llms/$slug.md': typeof LangLlmsSlugDotmdRoute
  '/$lang/llms/full': typeof LangLlmsFullRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang/$'
    | '/api/search'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/$lang/llms/$slug.md'
    | '/$lang/llms/full'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/$'
    | '/api/search'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/$lang/llms/$slug.md'
    | '/$lang/llms/full'
  id:
    | '__root__'
    | '/'
    | '/$lang/$'
    | '/api/search'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/$lang/llms/$slug.md'
    | '/$lang/llms/full'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangSplatRoute: typeof LangSplatRoute
  ApiSearchRoute: typeof ApiSearchRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  LangLlmsSlugDotmdRoute: typeof LangLlmsSlugDotmdRoute
  LangLlmsFullRoute: typeof LangLlmsFullRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/$': {
      id: '/$lang/$'
      path: '/$lang/$'
      fullPath: '/$lang/$'
      preLoaderRoute: typeof LangSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/llms/full': {
      id: '/$lang/llms/full'
      path: '/$lang/llms/full'
      fullPath: '/$lang/llms/full'
      preLoaderRoute: typeof LangLlmsFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/llms/$slug.md': {
      id: '/$lang/llms/$slug.md'
      path: '/$lang/llms/$slug.md'
      fullPath: '/$lang/llms/$slug.md'
      preLoaderRoute: typeof LangLlmsSlugDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangSplatRoute: LangSplatRoute,
  ApiSearchRoute: ApiSearchRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  LangLlmsSlugDotmdRoute: LangLlmsSlugDotmdRoute,
  LangLlmsFullRoute: LangLlmsFullRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
